### ISSUE TITLE
Bottom temperature plots dont display < 1999 data

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/ECSA#20]
@seanhardison1 @slarge 
The bot_temp_fall_spdf.rdata file in data-raw only contains data from 1999 data.

I don't see any R files (in data raw) that creates this data. The data files on the google drive do indeed have earlier years. 

Where is the code that processes the google drive data? Does it reside outside of this project?

**Comment by seanhardison1** [comment]
The files are too big to have on github uncompressed, but the code to process them is in data-raw/collapse_into_stack.R. Let me run it again locally and see what happens

**Comment by seanhardison1** [comment]
Not sure why older years weren't stacked but it's fixed now :man_shrugging:
