### ISSUE TITLE
st_transform(): which package?

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/ECSA#21]
@seanhardison1 
The function st_transform is used on line 34 of crop_to_strata.R
However both packages "stars" and "sf" have this function.  I know we are attaching the "stars" package but i also see "sf" listed in the description file. 

The same goes for as()

**Comment by seanhardison1** [comment]
Andy, both are exported from sf

**Comment by seanhardison1** [comment]
@andybeet I take that back. It appears that as() is exported from `methods`, but can be implemented for spatial classes

**Comment by andybeet** [comment]
@seanhardison1  ok. i'll fix it
