### ISSUE TITLE
data origin

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/ECSA#36]
https://github.com/NOAA-EDAB/ECSA/blob/e5816161c706ba32fa82a71591b943cb420f9f01/data-raw/collapse_into_stack.R#L97

@seanhardison1, where did this data come from? Is this from the files that Kevin uploaded to shared google drive e.g., RAST_atlmen_2018.00.00.PA.spri.0155.000000000.RData? I'm going to update for June assessments and I'm a tad stuck. Thanks

**Comment by seanhardison1** [comment]
Just emailed you a link
