### ISSUE TITLE
food habits dataset too big for github

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ECSA#8]
I tried putting Brian's Rdata file into the data folder but it exceeds the file size limit (100mb). 
Should we consider the [Git Large File Storage](https://git-lfs.github.com/), or would it be better to serve it from ERDDAP?

**Comment by slarge** [comment]
Another option (for branch folks with access to the branch drive) is to use [googledrive](https://googledrive.tidyverse.org/). I have some code bouncing around that will authenticate and facilitate downloading the data.

**Comment by seanhardison1** [comment]
ERDDAP would be good for this because it allows for subsetting data prior to download. If we're planning on hosting/accessing data through ERDDAP in the future anyways, then that's my vote.

**Comment by slarge** [comment]
I had started to edit my comment that the googledrive is a short-term solution and we should aim for ERDDAP, but we should just make sure it's OK with Brian
